export const CodeSandboxDependencies = [
    // "analytics-node",
    // "axios",
    // "brain.js",
    "chart.js",
    // "exceljs",
    // "jest",
    // "joi",
    // "math.js",
    // "moment-timezone",
    // "ml.js",
    // "natural",
    // "phaser.js",
    // "synaptic",
    // "tensorflow.js",
]