export const CodeSandboxDependencies = [
    // "analytics-node",
    // "axios",
    // "brain.js",
    ["chart.js", "^4.3.3"],
    ["d3", "^7.8.5"],
    // "exceljs",
    // "jest",
    // "joi",
    // "math.js",
    // "moment-timezone",
    // "ml.js",
    // "natural",
    // "phaser.js",
    // "synaptic",
    // "tensorflow.js",
]